-- ============================================
-- RAÍZES EDUCACIONAL - TABELAS DE JOGOS
-- Execute este SQL no Supabase SQL Editor
-- ============================================

-- Tabela de jogos disponíveis
CREATE TABLE IF NOT EXISTS jogos (
    id_jogo BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome TEXT NOT NULL,
    descricao TEXT,
    slug TEXT UNIQUE NOT NULL,
    habilitado BOOLEAN DEFAULT true,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Tabela de sessões de jogo
CREATE TABLE IF NOT EXISTS sessoes_jogo (
    id_sessao BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_crianca BIGINT REFERENCES criancas(id_crianca) ON DELETE CASCADE,
    id_jogo BIGINT REFERENCES jogos(id_jogo),
    data_hora TIMESTAMPTZ DEFAULT NOW(),
    finalizada BOOLEAN DEFAULT false,
    pontos INTEGER DEFAULT 0,
    acertos INTEGER DEFAULT 0,
    tentativas INTEGER DEFAULT 0,
    duracao_segundos INTEGER
);

-- Tabela de eventos durante as sessões
CREATE TABLE IF NOT EXISTS eventos_jogo (
    id_evento BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_sessao BIGINT NOT NULL REFERENCES sessoes_jogo(id_sessao) ON DELETE CASCADE,
    tipo_evento TEXT NOT NULL,
    data_hora TIMESTAMPTZ DEFAULT NOW(),
    dados_adicionais JSONB
);

-- Inserir jogos iniciais
INSERT INTO jogos (nome, descricao, slug, habilitado) VALUES
('Onde está o brinquedo!', 'Memória visual com grid adaptativo', 'onde-esta-o-brinquedo', true),
('Jogo #2', 'Em breve', 'em-breve-2', false),
('Jogo #3', 'Em breve', 'em-breve-3', false),
('Jogo #4', 'Em breve', 'em-breve-4', false)
ON CONFLICT (slug) DO NOTHING;

-- Habilitar RLS (Row Level Security)
ALTER TABLE sessoes_jogo ENABLE ROW LEVEL SECURITY;
ALTER TABLE eventos_jogo ENABLE ROW LEVEL SECURITY;

-- Políticas para sessões (através das crianças)
DROP POLICY IF EXISTS "Responsáveis podem ver sessões de suas crianças" ON sessoes_jogo;
CREATE POLICY "Responsáveis podem ver sessões de suas crianças" ON sessoes_jogo
    FOR SELECT USING (
        EXISTS (
            SELECT 1 FROM criancas c
            JOIN usuarios u ON c.id_responsavel = u.id_usuario
            WHERE c.id_crianca = sessoes_jogo.id_crianca 
            AND u.uuid = auth.uid()
        )
        OR id_crianca IS NULL
    );

DROP POLICY IF EXISTS "Responsáveis podem inserir sessões de suas crianças" ON sessoes_jogo;
CREATE POLICY "Responsáveis podem inserir sessões de suas crianças" ON sessoes_jogo
    FOR INSERT WITH CHECK (
        EXISTS (
            SELECT 1 FROM criancas c
            JOIN usuarios u ON c.id_responsavel = u.id_usuario
            WHERE c.id_crianca = sessoes_jogo.id_crianca 
            AND u.uuid = auth.uid()
        )
        OR id_crianca IS NULL
    );

DROP POLICY IF EXISTS "Responsáveis podem atualizar sessões de suas crianças" ON sessoes_jogo;
CREATE POLICY "Responsáveis podem atualizar sessões de suas crianças" ON sessoes_jogo
    FOR UPDATE USING (
        EXISTS (
            SELECT 1 FROM criancas c
            JOIN usuarios u ON c.id_responsavel = u.id_usuario
            WHERE c.id_crianca = sessoes_jogo.id_crianca 
            AND u.uuid = auth.uid()
        )
        OR id_crianca IS NULL
    );

-- Políticas para eventos (através das sessões)
DROP POLICY IF EXISTS "Responsáveis podem ver eventos das sessões de suas crianças" ON eventos_jogo;
CREATE POLICY "Responsáveis podem ver eventos das sessões de suas crianças" ON eventos_jogo
    FOR SELECT USING (
        EXISTS (
            SELECT 1 FROM sessoes_jogo sj
            LEFT JOIN criancas c ON sj.id_crianca = c.id_crianca
            LEFT JOIN usuarios u ON c.id_responsavel = u.id_usuario
            WHERE sj.id_sessao = eventos_jogo.id_sessao 
            AND (u.uuid = auth.uid() OR sj.id_crianca IS NULL)
        )
    );

DROP POLICY IF EXISTS "Responsáveis podem inserir eventos das sessões de suas crianças" ON eventos_jogo;
CREATE POLICY "Responsáveis podem inserir eventos das sessões de suas crianças" ON eventos_jogo
    FOR INSERT WITH CHECK (
        EXISTS (
            SELECT 1 FROM sessoes_jogo sj
            LEFT JOIN criancas c ON sj.id_crianca = c.id_crianca
            LEFT JOIN usuarios u ON c.id_responsavel = u.id_usuario
            WHERE sj.id_sessao = eventos_jogo.id_sessao 
            AND (u.uuid = auth.uid() OR sj.id_crianca IS NULL)
        )
    );

-- Políticas para jogos (leitura pública)
DROP POLICY IF EXISTS "Todos podem ver jogos" ON jogos;
CREATE POLICY "Todos podem ver jogos" ON jogos
    FOR SELECT USING (true);

-- Criar índices para melhor performance
CREATE INDEX IF NOT EXISTS idx_sessoes_crianca ON sessoes_jogo(id_crianca);
CREATE INDEX IF NOT EXISTS idx_sessoes_jogo ON sessoes_jogo(id_jogo);
CREATE INDEX IF NOT EXISTS idx_eventos_sessao ON eventos_jogo(id_sessao);

-- ============================================
-- FIM DA MIGRATION
-- ============================================
